### ISSUE TITLE
Root check is not working in my case

### ISSUE THREAD

**Issue by dvaqueiro** [Redominus/useful-scripts#1]
I run the ubuntu-php7.2.8.sh script with regular user and broke at the end of script instead in the inital check

https://github.com/Redominus/useful-scripts/blob/master/php/ubuntu-php7.2.8.sh#L2

**Comment by dvaqueiro** [comment]
Ops, i run with sh instead bash and thats is the problem...

Sorry.

**Comment by Redominus** [comment]
Check added to force running with bash when not making it executable.
